### ISSUE TITLE
urgent issue- sign up not working properly

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#942] opened 2022-09-25 13:17 UTC
sign up apparently not taking name.

**Comment by matkoniecz** [comment] 2022-09-25 13:38
@polly64 Is it about signing up with a very long username?

I see that for example registering with `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` username triggers

> Error: error: new row for relation "users" violates check constraint "users_username_len"

without explanation given to user, but registering with a shorter username (`aaaaaaaaaaaaaaaaaaaaaaaaaaaaa`) works fine.

Apparently length limit is off by one.

**Comment by matkoniecz** [comment] 2022-09-25 13:41
If that is the problem: then will be fixed by #943

If the problem is different: which exact username was used?

Was sign up on staging or on main server? Or on Colouring server used by Athens or someone else?

**Comment by polly64** [comment] 2022-09-25 13:47
thanks @matkoniecz it was on staging and it was a name without hyphens or numbers but I can ask Mike about this as meeting him tomorrow so don't worry about this one unless something makes immediate sense

**Comment by polly64** [comment] 2022-09-25 14:04
@mdsimpson42 could you possibly

- [ ] check the sign up is working ok on staging and main site - @matkoniecz has had a quick look and thought ok but someone I work with just had trouble getting on 
- [ ] also could we change the ' not- your real name' to 'please note the user name you choose will be public' or something like that
- [ ] let's chat re changing 'Please note that if you forget your password, you will only be able to recover your account if you provide an email address' to 'Our policy is to avoid collecting personal data wherever possible. An email address is only necessary if you wish to be able to recover your account should you forget your password'.

**Comment by matkoniecz** [comment] 2022-09-25 14:36
>  has had a quick look and thought ok but someone I work with just had trouble getting on

To be clear it is not working 100% OK

If someone is using long possible name allowed by the for then sign up will fail. https://github.com/colouring-cities/colouring-london/pull/943 will fix this

In meantime, as workaround one should select a bit shorter username

**Comment by polly64** [comment] 2022-09-25 16:14
@matkoniecz ok will ask them to try again

**Comment by matkoniecz** [comment] 2022-09-27 09:07
Maybe the strong request to avoid real name was done for GDPR/related reasons?

**Comment by matkoniecz** [comment] 2022-09-27 10:02
@mdsimpson42 - pinging as requested by @polly64

**Comment by mdsimpson42** [comment] 2022-10-03 08:31
Done. Sorry, for the delay!

**Closed** 2022-10-24 09:52 UTC
