### ISSUE TITLE
Prevent users from deleting data

### ISSUE THREAD

**Issue by mz8i** [colouring-cities/colouring-london#516] opened 2019-11-22 17:25 UTC
For discussion: users should not be able to just remove other users' contributions. Removing a value where there is one should be disallowed.

Potential exceptions (all would need more development):
- there should be admin / higher level users with that privilege
- a user can remove a data point that only they have edited - this would need going over the history of the attribute for that particular building and assembling a list of users that have edited. If the current user is the only one, they can remove - because someone can make a mistake and then want to remove it. But they shouldn't be able to first change someone else's data and then remove it completely.

A question is what happens when there is a value that is clearly wrong, and someone sees it. They might be tempted to replace it with another nonsensical value just to remove the incorrect one.

**Comment by mz8i** [comment] 2020-02-06 17:52
@polly64 @tomalrussell I think it's worth reaching an agreement on this issue and closing if it won't be implemented

**Comment by polly64** [comment] 2020-02-06 18:22
I would definitely like to keep the prevent deletion in place as I think people already have the option to remove by editing, and I also don't think editors should be able to discard others' work without a reason i.e by replacing the information.

**Comment by tomalrussell** [comment] 2022-07-26 11:47
Closing as older duplicate of #807

**Closed by tomalrussell** 2022-07-26 11:47 UTC
Labels: ui:community, api
