### ISSUE TITLE
streaming speed problem

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#1054] opened 2023-01-16 11:45 UTC
@matkoniecz @mdsimpson42 @fallipalaiologou 

The streaming speed for planning data is slower than for other layers which i'd expect. Just checked on my new computer , and also  with the Turing IT engineer's computer and loading the same  speed - also checked on firefox, safary and chrome most updated versions- all the same .
The problem seems to be worst when you zoom from london to close up- sometimes seems to just get stuck for ages is there anything we can do?  It's problematic when demoing because it needs to be seamless.  If you zxoom out some levels work fine but others load much more slowly- any thoughts for how we could speed up?

I think we will need to put a disclaimer on the section about variation of loading speed as streamed data so people don't get oput off. I will put on manual now

**Comment by matkoniecz** [comment] 2023-01-21 15:42
duplicate of  #1057

**Closed by matkoniecz** 2023-01-21 15:42 UTC
